# Generated by Django 3.2.20 on 2024-10-20 01:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reserva', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('numero_mesa', models.IntegerField()),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('hora_comienzo', models.TimeField()),
                ('personas', models.IntegerField()),
            ],
        ),
    ]
