# Generated by Django 5.1.2 on 2024-10-30 00:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='dia_reserva',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
