# Generated by Django 4.2 on 2024-12-11 00:41

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0003_auto_20241124_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='reserva',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='Código de Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dia_reserva',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Día de Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_comienzo',
            field=models.CharField(max_length=100, verbose_name='Hora de Comienzo'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_fin',
            field=models.CharField(max_length=100, verbose_name='Hora de Fin'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_mesa',
            field=models.IntegerField(verbose_name='Número de Mesa'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='personas',
            field=models.IntegerField(verbose_name='Número de Personas'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
    ]
