# Generated by Django 3.2.20 on 2024-11-22 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0004_auto_20241106_1958'),
        ('carrito', '0002_remove_carritoitem_variacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='carrito_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Carrito'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='fecha_agregado',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Agregado'),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad de Producto'),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='carro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrito.carrito', verbose_name='Carro'),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Está Activo?'),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
