# Generated by Django 3.2.20 on 2024-11-19 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_alter_pedido_direccion_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproducto',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='pedido.pedido'),
        ),
    ]
