# Generated by Django 4.2 on 2024-12-11 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_producto_ventas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedido', '0003_alter_pedido_direccion_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_id',
            field=models.CharField(max_length=100, verbose_name='Monto ID'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pago_id',
            field=models.CharField(max_length=100, verbose_name='ID de Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pago_method',
            field=models.CharField(max_length=100, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_1',
            field=models.CharField(max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Detalle Dirección (opcional)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='impuesto',
            field=models.FloatField(verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ip',
            field=models.CharField(blank=True, max_length=20, verbose_name='Dirección IP'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='¿Pedido realizado?'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedido.pago', verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pais',
            field=models.CharField(max_length=50, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_nota',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nota del Pedido (opcional)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_numero',
            field=models.CharField(max_length=20, verbose_name='Número de Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_total',
            field=models.FloatField(verbose_name='Total del Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='region',
            field=models.CharField(max_length=20, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('New', 'Nuevo'), ('Accepted', 'Aceptado'), ('Completed', 'Completado'), ('Cancelled', 'Cancelado')], default='New', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='¿Pedido Confirmado?'),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.pago', verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='pedido.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='producto_precio',
            field=models.FloatField(verbose_name='Precio del Producto'),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
