# Generated by Django 3.2.20 on 2024-10-17 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revisarrating',
            old_name='revisar',
            new_name='review',
        ),
    ]
