# Generated by Django 3.2.20 on 2024-11-06 22:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_remove_carritoitem_variacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedido', '0002_remove_pedidoproducto_variacion'),
        ('tienda', '0002_rename_revisar_revisarrating_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RevisarRating',
            new_name='ReseñaRating',
        ),
        migrations.DeleteModel(
            name='Variacion',
        ),
    ]
