# Generated by Django 3.2.20 on 2024-11-06 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20241106_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseñarating',
            old_name='review',
            new_name='reseña',
        ),
        migrations.RenameField(
            model_name='reseñarating',
            old_name='subject',
            new_name='titulo',
        ),
    ]
