# Generated by Django 3.2.20 on 2024-12-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_auto_20241106_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ventas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
