# Generated by Django 3.2.20 on 2024-11-22 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0004_auto_20241106_1958'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedido', '0004_alter_pedidoproducto_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código del cupón')),
                ('descuento', models.FloatField(verbose_name='Porcentaje de descuento')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de expiración')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('total_venta', models.FloatField(verbose_name='Total de la venta')),
                ('estado_pedido', models.CharField(choices=[('New', 'Nuevo'), ('In Progress', 'En proceso'), ('Shipped', 'Enviado'), ('Delivered', 'Entregado')], default='New', max_length=50)),
                ('region', models.CharField(max_length=50, verbose_name='Región')),
                ('pais', models.CharField(max_length=50, verbose_name='País')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la venta')),
                ('cupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.cupon', verbose_name='Cupón aplicado')),
                ('pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedido.pago', verbose_name='Método de pago')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido', verbose_name='Pedido relacionado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto', verbose_name='Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
