# Generated by Django 3.2.20 on 2024-11-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='horario',
        ),
        migrations.AddField(
            model_name='empleado',
            name='entrada',
            field=models.TimeField(default='14:00', verbose_name='Hora de entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='entrada_almuerzo',
            field=models.TimeField(default='14:00', verbose_name='Entrada de almuerzo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='salida',
            field=models.TimeField(default='00:00', verbose_name='Hora de salida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='salida_almuerzo',
            field=models.TimeField(default='00:00', verbose_name='Salida de almuerzo'),
            preserve_default=False,
        ),
    ]
