# Generated by Django 3.2.20 on 2024-11-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_auto_20241121_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='rut',
            field=models.CharField(default='00000000-0', max_length=12, unique=True, verbose_name='RUT del empleado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='entrada',
            field=models.TimeField(blank=True, default='00:00', null=True, verbose_name='Hora de entrada'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='entrada_almuerzo',
            field=models.TimeField(blank=True, default='00:00', null=True, verbose_name='Entrada de almuerzo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salida',
            field=models.TimeField(blank=True, default='00:00', null=True, verbose_name='Hora de salida'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salida_almuerzo',
            field=models.TimeField(blank=True, default='00:00', null=True, verbose_name='Salida de almuerzo'),
        ),
    ]
