# Generated by Django 3.2.20 on 2024-10-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
