# Generated by Django 3.2.20 on 2024-10-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_auto_20241001_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioperfil',
            name='region',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
