# Generated by Django 3.2.20 on 2024-11-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cuenta', '0006_auto_20241121_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece este usuario.', related_name='user_set', to='auth.Group', verbose_name='grupos'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='user_set', to='auth.Permission', verbose_name='permisos de usuario'),
        ),
    ]
